# Generated by Django 5.2.10 on 2026-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('GL', 'Global')], default='GL', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('GL', 'Global')], default='GL', max_length=2)),
                ('category', models.CharField(choices=[('WORLD', 'World'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports'), ('SCIENCE', 'Science'), ('HEALTH', 'Health')], default='WORLD', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary', null=True)),
                ('sentiment', models.CharField(blank=True, help_text='positive, negative, or neutral', max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='AI-generated tags')),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx'), models.Index(fields=['continent', '-published_at'], name='news_newsar_contine_555f3d_idx'), models.Index(fields=['category', '-published_at'], name='news_newsar_categor_378b25_idx')],
            },
        ),
    ]
