# Generated by Django 5.2.10 on 2026-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='district',
            field=models.CharField(blank=True, help_text='District name for local news', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='indian_state',
            field=models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('JK', 'Jammu & Kashmir'), ('LA', 'Ladakh'), ('PY', 'Puducherry'), ('CH', 'Chandigarh')], help_text='Indian state for regional news', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_indian_news',
            field=models.BooleanField(default=False, help_text='Flag for India-focused news'),
        ),
    ]
