# Generated by Django 5.2.10 on 2026-01-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_district_newsarticle_indian_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('WORLD', 'World'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports'), ('SCIENCE', 'Science'), ('HEALTH', 'Health'), ('BUDGET', 'Budget 2026')], default='WORLD', max_length=20),
        ),
    ]
