# Generated by Django 5.2.10 on 2026-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='credibility_score',
            field=models.FloatField(default=0.0, help_text='AI credibility score (0-100). 80+: Verified, 50-80: Unverified, <50: Disputed'),
        ),
    ]
