# Generated by Django 5.2.10 on 2026-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_credibility_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='epaper_page',
            field=models.IntegerField(default=1, help_text='Page number in ePaper edition (1-based)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='epaper_position',
            field=models.IntegerField(default=0, help_text='Position within page (0=top, higher=lower)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='epaper_section',
            field=models.CharField(default='FRONT_PAGE', help_text='ePaper section: FRONT_PAGE, CITY, NATION, WORLD, BUSINESS, SPORTS, ENTERTAINMENT', max_length=50),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='epaper_size',
            field=models.CharField(default='MEDIUM', help_text='Article size in ePaper: LARGE, MEDIUM, SMALL', max_length=20),
        ),
    ]
