# Generated by Django 5.2.10 on 2026-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_epaper_page_newsarticle_epaper_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Publication date of the paper', unique=True)),
                ('pdf_file', models.FileField(help_text='Upload the daily newspaper PDF file', upload_to='daily_papers/%Y/%m/')),
                ('edition', models.CharField(default='Delhi Edition', help_text='Edition name (e.g., Delhi Edition, Mumbai Edition)', max_length=100)),
                ('total_pages', models.IntegerField(default=1, help_text='Total number of pages in the paper')),
                ('file_size', models.CharField(blank=True, help_text='File size (auto-calculated)', max_length=50)),
                ('is_published', models.BooleanField(default=True, help_text='Make this paper visible to users')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Paper',
                'verbose_name_plural': 'Daily Papers',
                'ordering': ['-date'],
            },
        ),
    ]
