# Generated by Django 5.2.10 on 2026-01-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_dailypaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypaper',
            name='pdf_content',
            field=models.JSONField(blank=True, default=list, help_text='Extracted articles from PDF (auto-generated)'),
        ),
    ]
