# Generated by Django 5.2.10 on 2026-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_dailypaper_pdf_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_translated',
            field=models.BooleanField(default=False, help_text='True if title/description were machine-translated to English'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='original_description',
            field=models.TextField(blank=True, help_text='Original non-English description before translation', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='original_language',
            field=models.CharField(blank=True, default='', help_text="Detected source language code, e.g. 'hi', 'ta', 'te', 'en'", max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='original_title',
            field=models.CharField(blank=True, default='', help_text='Original non-English title before translation', max_length=500),
        ),
    ]
